### ISSUE TITLE
NullException error

### ISSUE THREAD

**Issue by maxdup** [ruarai/CompilePal#109]
version 27.8

**Debug.log**

CompilePal - Cubemap Generator
Detecting HDR levels...
Map requires one set of cubemaps
Compiling cubemaps...
Cubemaps compiled
An exception was caught by the ExceptionHandler:
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at CompilePalX.CompilingManager.CompileThreaded() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compiling\CompilingManager.cs:line 114
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

full log: https://pastebin.com/HdegrzEy

It seems to crash between cubemaps and repacking

Reported to me by Benroads. Ask me or him for additional context but I feel this should be an easy fix.

**Comment by Exactol** [comment]
I think this was fixed in a2dd282, Can you tell them to try this version?
[Compile Pal 027.9.zip](https://github.com/ruarai/CompilePal/files/4482825/Compile.Pal.027.9.zip)

**Comment by maxdup** [comment]
It seems to have been fixed. Thank you
