### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by Dragostai** [ruarai/CompilePal#156]
Whenever i try to compile the map this error comes up, i tried using old versions to fix it, starting in admin mode or starting in compatibility mode but none of them fixed it. İ saw that someone else got the same error here, but nobody mentioned how to fix it.
that's the error: 

Starting a 'Normal' compile.
Starting compilation of nmo_anomaly
An exception was caught by the ExceptionHandler:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.CompileExecutable.Run(CompileContext c) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\CompileExecutable.cs:line 47
   at CompilePalX.CompilingManager.CompileThreaded() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compiling\CompilingManager.cs:line 112
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Exactol** [comment]
Can you send the gameConfigs.json in the CompilePal/GameConfiguration folder?

**Comment by Dragostai** [comment]
> Can you send the gameConfigs.json in the CompilePal/GameConfiguration folder?

sure 


[
  {
    "GameFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\nmrih",
    "VBSP": ".\\vbsp.exe",
    "VVIS": ".\\vvis.exe",
    "VRAD": ".\\vrad.exe",
    "BSPZip": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\bin\\bspzip.exe",
    "VBSPInfo": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\bin\\vbspinfo.exe",
    "VPK": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\bin\\vpk.exe",
    "GameEXE": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\hl2.exe",
    "MapFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\nmrih\\maps",
    "SDKMapFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\sourcesdk_content\\nmrih\\mapsrc",
    "BinFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\nmrih\\bin",
    "Name": "No More Room in Hell"
  }
]

**Comment by Exactol** [comment]
Can you try deleting the gameConfigs.json file, opening hammer, and then launching Compile Pal?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
