### ISSUE TITLE
System.ArgumentOutOfRangeException during Packing step of compiling

### ISSUE THREAD

**Issue by ITstumbler** [ruarai/CompilePal#159]
CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: D:\Steam\SteamApps\common\Team Fortress 2\tf\custom\
Found search path: D:\Steam\SteamApps\common\Team Fortress 2\tf
Found search path: D:\Steam\SteamApps\common\Team Fortress 2\tf
Found search path: D:\Steam\SteamApps\common\Team Fortress 2\tf\bin
Found search path: D:\Steam\SteamApps\common\Team Fortress 2\tf\download
Reading BSP...
Initializing pak file...
Something broke:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at CompilePalX.Compilers.UtilityProcess.ParticleUtils.ReadParticle(String filePath) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\Utility\ParticleUtils.cs:line 284
   at CompilePalX.Compilers.BSPPack.PakFile.AddParticle(String internalPath) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 334
   at CompilePalX.Compilers.BSPPack.PakFile..ctor(BSP bsp, List`1 sourceDirectories, List`1 includeFiles, List`1 excludedFiles, List`1 excludedDirs, List`1 excludedVpkFiles, String outputFile) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 109
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 246
An error cancelled the compile.
Compile forcefully ended.

Seems to not have happened before the Scream Fortress update.

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
