### ISSUE TITLE
Compile pal 27.27 doesn't pack the content into gmod (I use the custom content from l4d2)

### ISSUE THREAD

**Issue by Mngdd** [ruarai/CompilePal#179]
LOG:
```
CompilePal - Cubemap Generator
Detecting HDR levels...
Failed to run executable: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\vbspinfo.exe
Could not read HDR levels, defaulting to one.
Map requires one set of cubemaps
Compiling cubemaps...
Cubemaps compiled

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Source directories:
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\greenwood_estate_(murder)_286757719
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Something broke:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\bspzip.exe' with working directory 'C:\Users\USER\Desktop\HAMMER\Compile Pal 027.27'. Не удается найти указанный файл.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.BSPPack.BSPPack.UnpackBSP(String unpackDir) in C:\Users\10zil\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 492
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context, CancellationToken cancellationToken) in C:\Users\10zil\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 262
An error cancelled the compile.
Compile forcefully ended.

'Publish - Both' compile finished in 00:08:05
```

used publish both compile

**Comment by Mngdd** [comment]
it creates cubemaps, but doesn't pack the content

**Comment by Exactol** [comment]
Does this path exist? C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\bin\bspzip.exe

**Comment by Mngdd** [comment]
No, should I put it here?

**Comment by Exactol** [comment]
Unfortunately this is a Garrys Mod issue, certain betas like x86 don't have bspzip.exe for some reason (#134)
