### ISSUE TITLE
Error when packing .bsp and the .bsp contains custom models

### ISSUE THREAD

**Issue by Myst-vi** [ruarai/CompilePal#203]
**X28**

**Describe the bug**
Something broke:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CompilePalX.Compilers.BSPPack.BSP.buildModelList() in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 306
   at CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 100
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context, CancellationToken cancellationToken) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 223
An error cancelled the compile.
Compile forcefully ended.

**Steps to reproduce**
Only happends when compiling "pack" and the .bsp exists contains custom models.

**Expected behavior**
Trying to pack textures to my .bsp, which works until i used custom .mdl files

**Debug.log**
Please upload the debug.log file found in your Compile Pal folder.

**Crash logs**
If applicable, please upload crash logs found in the CrashLog folder.

**Additional context**
I am totally new to CompilePal, so may i am just doing a "noob" error?

EDIT: the .bsp was compiled with Hammer from Momentum Mod.

i recompiled with my hammer++ and CS:GO setting, then chose csgo in CompilePal and it worked.

[debug.log](https://github.com/ruarai/CompilePal/files/11105221/debug.log)

**Comment by Exactol** [comment]
You aren't doing anything wrong, I think a recent update to the Momentum Mod BSP format broke packing. I'll try to get a fix out soon
