### ISSUE TITLE
How do I solve "File name has not been provided"

### ISSUE THREAD

**Issue by circuschaser** [ruarai/CompilePal#241]
**Compile Pal Version**

**Describe the bug**
Pack fails immediately.
**System.InvalidOperationException: Cannot start process because a file name has not been provided.**

**Steps to reproduce**
![CompilePal screenshot](https://github.com/ruarai/CompilePal/assets/4381255/835d96bc-03ac-42f3-ad57-e51cdc795f82)

**Expected behavior**
Expected to pack a bsp with assets.

**Debug.log**
Starting a 'Pack' compile.
Starting compilation of redeemer

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\
Found wildcard path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency\content\
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Source directories:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\workshop
E:\SteamLibrary\steamapps\common\insurgency2\insurgency
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Reading BSP...
Something broke:
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.BSPPack.BSPPack.UnpackBSP(String unpackDir) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 470
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context, CancellationToken cancellationToken) in D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 238
An error cancelled the compile.
Compile forcefully ended.

'Pack' compile finished in 00:00:00

**Additional context**

**Comment by circuschaser** [comment]
Forgot to note that the BSP was compiled successfully by CompilePal from a Hammer project.

**Comment by Exactol** [comment]
Can you open the game configuration in Compile Pal and see if there is a path to BSPZip, and if so, check if the program exists at the location? You can view the game configuration by clicking the 3 dots on the Game Selector screen and clicking Edit.
![image](https://github.com/ruarai/CompilePal/assets/15372675/d3d0880b-df4f-4272-ac1d-ea0b3a4c6a1a)

**Comment by circuschaser** [comment]
Thanks for the reply.
BSPZip was missing. Here's the JSON of the configuration:

[
  {
    "GameFolder":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\insurgency",
    "VBSP":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\bin\\vbsp.exe",
    "VVIS":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\bin\\vvis.exe",
    "VRAD":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\bin\\vrad.exe",
*    "BSPZip": null,*
    "VBSPInfo": null,
    "VPK": "E:\\SteamLibrary\\steamapps\\common\\insurgency2\\bin\\vpk.exe",
    "GameEXE":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\insurgency.exe",
    "MapFolder":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\insurgency\\maps",
    "SDKMapFolder":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\sdk_content\\maps",
    "BinFolder": "E:\\SteamLibrary\\steamapps\\common\\insurgency2\\bin",
    "Name": "Insurgency",
    "GameInfoPath":
"E:\\SteamLibrary\\steamapps\\common\\insurgency2\\insurgency\\gameinfo.txt",
    "SteamAppID": 222880
  }
]

I downloaded a BSPZip.exe file from here:
https://www.pconlife.com/download/otherfile/86126/99005ec0c680eaf12eba20dd9a2b6f26/

Added it to CompilePal
[image: newBSPZip.PNG]

Ran the pack again, still got this:

Starting a 'Pack' compile.
Starting compilation of redeemer_coop

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\
Found wildcard path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\content\
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
Found search path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Source directories:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\workshop
E:\SteamLibrary\steamapps\common\insurgency2\insurgency
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Reading BSP...
Something broke:
System.InvalidOperationException: Cannot start process because a file name
has not been provided.
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.BSPPack.BSPPack.UnpackBSP(String unpackDir) in
D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 470
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context,
CancellationToken cancellationToken) in
D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 238
An error cancelled the compile.
Compile forcefully ended.

'Pack' compile finished in 00:00:00

[image: CompilePal_fail_0621.PNG]



Rob Howard
404 422 3210
***@***.***

**Comment by circuschaser** [comment]
vbspinfo.exe obviously missing as well, so I got a copy of that and added
it.
Ran CompilePal again.
Got this:

Starting a 'Pack' compile.
Starting compilation of redeemer_coop

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\
Found wildcard path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\content\
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path: E:\SteamLibrary\steamapps\common\insurgency2\insurgency
Found search path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
Found search path:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Source directories:
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\custom\workshop
E:\SteamLibrary\steamapps\common\insurgency2\insurgency
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\bin
E:\SteamLibrary\steamapps\common\insurgency2\insurgency\download
Reading BSP...
Initializing pak file...
Writing file list...
Running bspzip...
BSPZIP exited with code: -1073741511
Finished!
---------------------
0 materials found
0 models found
0 particle files found
0 sounds found
Additional Files:
-Detail file
---------------------

'Pack' compile finished in 00:00:00
1 errors/warnings logged:
  1 errors/warnings logged for redeemer_coop:
    ● 1x: Warning: BSPZIP exited with code: -1073741511




Rob Howard
404 422 3210
***@***.***

**Comment by Exactol** [comment]
If BSPZip/vbspinfo doesnt come with the game then it may not support packing custom content into the map. Its possible you need to create a VPK, similar to l4d2. You could also try a tool that doesn't rely on bspzip like VIDE

**Comment by circuschaser** [comment]
Thanks, I'll check it out.
