### ISSUE TITLE
Unable to pack content

### ISSUE THREAD

**Issue by Xulua1499** [ruarai/CompilePal#32]
Getting the following error after successfully compiling the map:

```
Initializing pak file...
Something broke:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterials(String path, List`1 skins)
   at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins)
   at CompilePalX.Compilers.BSPPack.PakFile..ctor(BSP bsp, List`1 sourceDirectories)
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)
```

Here is the compilepal log file:

```
Starting a 'Fast' compile.
Starting compilation of C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.vmf
Valve Software - vbsp.exe (Oct 13 2015)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.vmf
material "maps/stone/rock1024_01_stw" not found.
Material not found!: MAPS/STONE/ROCK1024_01_STW
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
material "maps/verticality/blends/blend_panj_wall_02_03" not found.
Material not found!: MAPS/VERTICALITY/BLENDS/BLEND_PANJ_WALL_02_03
material "maps/wall/cement_wall04_spi" not found.
Material not found!: MAPS/WALL/CEMENT_WALL04_SPI
material "maps/revolt/rev_plasterbase_01" not found.
Material not found!: MAPS/REVOLT/REV_PLASTERBASE_01
Can't find surfaceprop asphalt for material CONCRETE/ROAD01, using default
Can't find surfaceprop asphalt for material CONCRETE/ROADPARKINGLOT, using default
Can't find surfaceprop sheetrock for material PLASTER/PLASTER_INT_18, using default
Can't find surfaceprop wet for material PLASTER/ROOFFLOOR_TAR01, using default
Can't find surfaceprop asphalt for material CONCRETE/ROADCROSSWALK_SMALL_NOBUMP, using default
material "maps/afghanistan/afg_blendwall_02" not found.
Material not found!: MAPS/AFGHANISTAN/AFG_BLENDWALL_02
material "maps/plaster/ir_plaster02a" not found.
Material not found!: MAPS/PLASTER/IR_PLASTER02A
material "maps/ramadi/concretefloor_01" not found.
Material not found!: MAPS/RAMADI/CONCRETEFLOOR_01
material "maps/market/mog_exterior_wall_02" not found.
Material not found!: MAPS/MARKET/MOG_EXTERIOR_WALL_02
Can't find surfaceprop metalsheet for material MAPS/METAL/METALSHEET_SHANTY_02, using default
Could not locate 'GameData' key in c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\gameinfo.txt
Patching WVT material: maps/rp_test_mrpv1/maps/terrain/buhriz_sandrubble_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/maps/afghanistan/afg_blendwall_07_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/blend/blend_moss_002_dirt_001_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/blend/blend_rock_003_moss_002_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/blend/blend_moss_002_dirt_006_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/concrete/blend_blacktop_02_wvt_patch
Patching WVT material: maps/rp_test_mrpv1/nature/blenddirtmud02_wvt_patch
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (1)
Processing areas...done (0)
Building Faces...done (0)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 2880 detail faces...done (0)
Merging details...done (0)
FixTjuncs...
PruneNodes...
WriteBSP...
done (1)
writing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.prt...Building visibility clusters...
done (0)
Creating default LDR cubemaps for env_cubemap using skybox materials:
   skybox/sky_day03_06*.vmt
 ! Run buildcubemaps in the engine to get the correct cube maps.
Creating default HDR cubemaps for env_cubemap using skybox materials:
   skybox/sky_day03_06*.vmt
 ! Run buildcubemaps in the engine to get the correct cube maps.
Finding displacement neighbors...
Finding lightmap sample positions...
Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
Building Physics collision data...

qhull precision error: Only 4 facets remain.  Can not merge another
pair.  The convexity constraints may be too strong.  Reduce the
magnitude of 'Cn' or increase the magnitude of 'An'.  For example,
try 'C-0.001' instead of 'C-0.1' or 'A-0.999' instead of 'A-0.9'.
done (2) (1515881 bytes)
Placing detail props : 0...1...2...3...4...5...6...7...8...9.Material MAPS/TERRAIN/BUHRIZ_SANDRUBBLE uses unknown detail object type escort01!
..10
Water found with no water_lod_control entity, creating a default one.
Compacting texture/material tables...
Reduced 6118 texinfos to 4450
Reduced 257 texdatas to 218 (9516 bytes to 7925)
Writing C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.bsp
Wrote ZIP buffer, estimated size 2208569, actual size 2193883
11 seconds elapsed
CMaterialDict::Shutdown m_MissingList count: 8
  -279.603210 133.299194 0.000000
  -282.854401 133.299194 0.000000
  -286.105591 136.550400 0.000000
  -286.105591 133.299194 0.000000
make_triangles:calc_triangle_representation: Cannot convert
  -1.828800 0.203200 0.000000
  -2.032000 6.096000 0.000000
  2.032000 6.096000 0.000000
  -1.828800 6.096000 0.000000
make_triangles:calc_triangle_representation: Cannot convert
  -1.828800 0.203200 0.000000
  -2.032000 6.096000 0.000000
  2.032000 6.096000 0.000000
  -1.828800 6.096000 0.000000
make_triangles:calc_triangle_representation: Cannot convert
  1.049162 -3.207047 0.000000
  -1.049033 -3.207047 0.000000
  -1.049033 3.206336 0.000000
  1.015345 -3.207047 0.000000
make_triangles:calc_triangle_representation: Cannot convert
Valve Software - vvis.exe (Oct 13 2015)
fastvis = true
nosort = true
4 threads
reading c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\maps\rp_test_mrpv1.bsp
reading c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\maps\rp_test_mrpv1.prt
 637 portalclusters
1645 numportals
BasePortalVis:       0...1...2...3...4...5...6...7...8...9...10 (0)
Optimized: 4404 visible clusters (2.93%)
Total clusters visible: 150309
Average clusters visible: 235
Building PAS...
Average clusters audible: 484
visdatasize:78463  compressed from 101920
writing c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\maps\rp_test_mrpv1.bsp
0 seconds elapsed
Valve Software - vrad.exe SSE (Oct 13 2015)

      Valve Radiosity Simulator     
4 threads
[Reading texlights from 'lights.rad']
[2 texlights parsed from 'lights.rad']

Loading c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\maps\rp_test_mrpv1.bsp
Error! Unable to load file "models/static_props/barrel_01_multiple.dx80.vtx"
Error! Unable to load file "models/static_props/container_01_closed.dx80.vtx"
Error! Unable to load file "models/static_props/pallet_caches_01.dx80.vtx"
Error! Unable to load file "models/static_props/container_01_open2.dx80.vtx"
Error! Unable to load file "models/static_props/container_01_open.dx80.vtx"
Error! Unable to load file "models/static_fittings/prop_stoop_96_16_32_2.dx80.vtx"
Error! Unable to load file "models/static_fittings/prop_stoop_64_16_32.dx80.vtx"
Error! Unable to load file "models/static_props/c4_static_prop.dx80.vtx"
Error! Unable to load file "models/static_fittings/fluorescent_light_01.dx80.vtx"
Error! Unable to load file "models/static_appliances/cables_01_long.dx80.vtx"
Error! Unable to load file "models/static_appliances/cables_01_short.dx80.vtx"
Error! Unable to load file "models/static_appliances/cable_box_04.dx80.vtx"
Error! Unable to load file "models/static_appliances/cable_box_02.dx80.vtx"
Error! Unable to load file "models/static_props/barrel_01_single.dx80.vtx"
Error! Unable to load file "models/furniture/foldingtable_folded.dx80.vtx"
Error! Unable to load file "models/props/rubble_pieces/rubble_02.dx80.vtx"
Error! Unable to load file "models/static_fittings/light04b.dx80.vtx"
Error! Unable to load file "models/static_fittings/electric_equipmentcluster03.dx80.vtx"
Error! Invalid VTX file checksum: -1016378617, expected -307952802 "models/furniture/foldingtable.dx80.vtx"
Error! Unable to load file "models/siege/prop_stool1960.dx80.vtx"
Error! Unable to load file "models/siege/prop_garagetools4.dx80.vtx"
Error! Unable to load file "models/siege/prop_garagetools3.dx80.vtx"
Error! Unable to load file "models/physics_props/electronics/cellphone_01.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_electronicmd05.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_electroniclg04.dx80.vtx"
Error! Unable to load file "models/physics_props/electronics/vcr_05.dx80.vtx"
Error! Unable to load file "models/siege/prop_toolboard0a.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_appliancelg04.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_appliancelg05.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_appliancelg01.dx80.vtx"
Error! Unable to load file "models/physics_props/boxes/box_electroniclg03.dx80.vtx"
Error! Unable to load file "models/static_fittings/window_frame_02_40x60.dx80.vtx"
Error! Unable to load file "models/static_furniture/chair_03.dx80.vtx"
Error! Unable to load file "models/physics_props/electronics/boombox_03.dx80.vtx"
Error! Unable to load file "models/siege/prop_garagetools1.dx80.vtx"
Error! Unable to load file "models/static_fittings/work_light_lamps.dx80.vtx"
Error! Unable to load file "models/static_fittings/work_light.dx80.vtx"
Error! Unable to load file "models/static_fittings/ir_satellite_dish_roofmount_01.dx80.vtx"
Error! Unable to load file "models/static_fittings/ir_satellite_dish_roofmount_02.dx80.vtx"
Error! Unable to load file "models/static_fittings/ir_satellite_dish_wallmount_01.dx80.vtx"
Error! Unable to load file "models/static_fittings/ir_satellite_dish_wallmount_03.dx80.vtx"
Error! Unable to load file "models/iraq/ir_hesco_basket_01_row.dx80.vtx"
Error! Unable to load file "models/static_fittings/prop_framing_door_112_single.dx80.vtx"
Error! Unable to load file "models/static_junk/filthy_mattress_02.dx80.vtx"
Error! Unable to load file "models/static_props/wcache_box_01.dx80.vtx"
Error! Unable to load file "models/siege/prop_cable15x137_0.dx80.vtx"
Error! Unable to load file "models/static_furniture/wall_painting_01_memorial.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_007.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_005b.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_007b.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_006.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_004.dx80.vtx"
Error! Unable to load file "models/props_foliage/rock_005.dx80.vtx"
Error! Unable to load file "models/static_props/wcache_ins_01_destr.dx80.vtx"
Error! Unable to load file "models/static_rubble/metal_sheet_01.dx80.vtx"
Error! Unable to load file "models/static_rubble/prop_rubble_plank_a.dx80.vtx"
Error! Unable to load file "models/static_rubble/prop_rubble_plank_b.dx80.vtx"
Error! Unable to load file "models/static_rubble/prop_rubble_plank_d.dx80.vtx"
Error! Unable to load file "models/static_rubble/prop_rubble_plank_c.dx80.vtx"
Error! Unable to load file "models/static_fittings/door_01_frame.dx80.vtx"
Error! Unable to load file "models/static_junk/woodencrate_01.dx80.vtx"
Error! Unable to load file "models/static_afghan/prop_interior_lamp.dx80.vtx"
Error! Unable to load file "models/static_afghan/prop_framing_beam_small_b.dx80.vtx"
Error! Unable to load file "models/static_furniture/table_small.dx80.vtx"
Error! Unable to load file "models/static_fittings/window_frame_01.dx80.vtx"
Error! Unable to load file "models/static_fittings/prop_framing_window_standard.dx80.vtx"
Error! Unable to load file "models/static_afghan/prop_afg_rugs_flat_b.dx80.vtx"
Error! Unable to load file "models/static_props/prop_interior_table_small.dx80.vtx"
Error! Unable to load file "models/static_props/papers_stack_02.dx80.vtx"
Error! Unable to load file "models/static_props/papers_stack_01.dx80.vtx"
Error! Unable to load file "models/siege/prop_stairshandrail0_cap.dx80.vtx"
Error! Unable to load file "models/siege/prop_stairshandrail0_64.dx80.vtx"
Error! Unable to load file "models/siege/prop_stairshandrail0_32.dx80.vtx"
Error! Unable to load file "models/static_fittings/ceiling_light02a.dx80.vtx"
Error! Unable to load file "models/static_fittings/light04a.dx80.vtx"
Error! Unable to load file "models/static_furniture/mattress.dx80.vtx"
Error! Unable to load file "models/static_props/wcache_crate_01.dx80.vtx"
Error! Unable to load file "models/static_props/ir_computerlab_station.dx80.vtx"
Error! Unable to load file "models/physics_props/electronics/keyboard_02.dx80.vtx"
Error! Invalid VTX file checksum: 1122989676, expected 124341422 "models/generic/ammocrate3.dx80.vtx"
Error! Unable to load file "models/static_props/wcache_crate_03.dx80.vtx"
Error! Unable to load file "models/static_furniture/locker01_single.dx80.vtx"
Error! Unable to load file "models/static_furniture/locker01_single02.dx80.vtx"
Error! Unable to load file "models/static_pipes/pipeset16_128straight.dx80.vtx"
Error! Unable to load file "models/static_pipes/pipeset16_bend90.dx80.vtx"
Error! Unable to load file "models/static_fittings/electric_equipmentcluster06.dx80.vtx"
Error! Unable to load file "models/static_afghan/afg_window_medium.dx80.vtx"
Error! Unable to load file "models/props_nature/campfire.dx80.vtx"
Error! Invalid VTX file checksum: -1989648022, expected -1849106627 "models/props_nature/puddle_001.dx80.vtx"
Error! Invalid VTX file checksum: 1303719054, expected 1035761079 "models/props_urban/concrete_car_stop001.dx80.vtx"
Error! Invalid VTX file checksum: -404225048, expected -551091331 "models/props_equipment/firehosebox01.dx80.vtx"
Error! Invalid VTX file checksum: -1044252778, expected -1980529911 "models/props_docks/marina_firehosebox.dx80.vtx"
Error! Invalid VTX file checksum: 1441758039, expected 1547259282 "models/props_urban/air_conditioner001.dx80.vtx"
Error! Invalid VTX file checksum: -428703672, expected -2055839595 "models/props_interiors/side_table_square.dx80.vtx"
Error! Unable to load file "models/props_furniture/it_mkt_table2.dx80.vtx"
Error! Unable to load file "models/props_interiors/ceda_table_maps.dx80.vtx"
Error! Invalid VTX file checksum: 2019958384, expected 2053744288 "models/props_foliage/pine_001_extralarge.dx80.vtx"
Error! Invalid VTX file checksum: 2735722, expected -1057738346 "models/props_foliage/spruce_001_small.dx80.vtx"
Setting up ray-trace acceleration structure... Done (13.78 seconds)
13054 faces
3 degenerate faces
9018418 square feet [1298652160.00 square inches]
558 Displacements
3443624 Square Feet [495881856.00 Square Inches]
13051 patches before subdivision
13051 patches after subdivision
227 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (65)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (6)
transfers 1781942, max 2813
transfer lists:  13.6 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #1 added RGB(20960, 7854, 3280)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #2 added RGB(2100, 811, 316)
Build Patch/Sample Hash Table(s).....Done<0.0919 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (4)
FinalLightFace Done
0 of 0 (0% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (14)
Writing leaf ambient...done
Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                 154/1024         7392/49152    (15.0%) 
brushes               4019/8192        48228/98304    (49.1%) 
brushsides           35459/65536      283672/524288   (54.1%) 
planes               29684/65536      593680/1310720  (45.3%) 
vertexes             26168/65536      314016/786432   (39.9%) 
nodes                 2572/65536       82304/2097152  ( 3.9%) 
texinfos              4450/12288      320400/884736   (36.2%) 
texdata                218/2048         6976/65536    (10.6%) 
dispinfos              558/0           98208/0        ( 0.0%) 
disp_verts           37526/0          750520/0        ( 0.0%) 
disp_tris            58272/0          116544/0        ( 0.0%) 
disp_lmsamples     6024324/0         6024324/0        ( 0.0%) 
faces                13054/65536      731024/3670016  (19.9%) 
hdr faces                0/65536           0/3670016  ( 0.0%) 
origfaces            10817/65536      605752/3670016  (16.5%) 
leaves                2727/65536       87264/2097152  ( 4.2%) 
leaffaces            15568/65536       31136/131072   (23.8%) 
leafbrushes           6745/65536       13490/131072   (10.3%) 
areas                    2/256            16/2048     ( 0.8%) 
surfedges           110579/512000     442316/2048000  (21.6%) 
edges                72012/256000     288048/1024000  (28.1%) 
LDR worldlights        227/8192        19976/720896   ( 2.8%) 
HDR worldlights          0/8192            0/720896   ( 0.0%) 
leafwaterdata            2/32768          24/393216   ( 0.0%) 
waterstrips           2020/32768       20200/327680   ( 6.2%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices         42372/65536       84744/131072   (64.7%) 
cubemapsamples          24/1024          384/16384    ( 2.3%) 
overlays               130/512         45760/180224   (25.4%) 
LDR lightdata         [variable]    30879076/0        ( 0.0%) 
HDR lightdata         [variable]           0/0        ( 0.0%) 
visdata               [variable]       78463/16777216 ( 0.5%) 
entdata               [variable]      293693/393216   (74.7%) 
LDR ambient table     2727/65536       10908/262144   ( 4.2%) 
HDR ambient table     2727/65536       10908/262144   ( 4.2%) 
LDR leaf ambient      7797/65536      218316/1835008  (11.9%) 
HDR leaf ambient      2727/65536       76356/1835008  ( 4.2%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/360110   ( 0.0%) 
pakfile               [variable]     2193883/0        ( 0.0%) 
physics               [variable]     1515881/4194304  (36.1%) 
physics terrain       [variable]      106912/1048576  (10.2%) 

Level flags = 0

Total triangle count: 40856
Writing c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\maps\rp_test_mrpv1.bsp
1 minute, 43 seconds elapsed
C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.bsp -> C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Source\cstrike\maps\rp_test_mrpv1.bsp
0 File(s) copied
'Fast' compile finished in 00:01:55
13 errors/warnings logged:
(1) - Material not found!: [sub:1] (Caution)
(2) - Material not found!: [sub:1] (Caution)
(3) - Material not found!: [sub:1] (Caution)
(4) - Material not found!: [sub:1] (Caution)
(5) - Material not found!: [sub:1] (Caution)
(6) - Material not found!: [sub:1] (Caution)
(7) - Material not found!: [sub:1] (Caution)
(8) - Material not found!: [sub:1] (Caution)
(9) - Material [sub:1] uses unknown detail object type [sub:2]!  (Caution)
(10) - make_triangles:calc_triangle_representation: Cannot convert (Warning)
(11) - make_triangles:calc_triangle_representation: Cannot convert (Warning)
(12) - make_triangles:calc_triangle_representation: Cannot convert (Warning)
(13) - fastvis = true (Info)
```

Not really got much info past this, it's using a bunch of custom content. Models, materials etc. I've compiled other maps just fine before.

**Comment by maxdup** [comment]
Not going to lie, this log is quite a mess, I honestly don't know where to start. Are you getting those vbsp/vrad errors in hammer as well? specifically "Error! Unable to load file X" and "Could not locate 'GameData' key in c:\program files (x86)\steam\steamapps\common\counter-strike source\cstrike\gameinfo.txt"

**Comment by Xulua1499** [comment]
I typically see missing VTX files with past compiles, but haven't noticed an issue with it before. I believe it's something to-do with LOD's, but isn't required? However I guess the model may be referencing one.

There are also a few missing textures actually in hammer and in-game too. It's a huge map, mostly everything is propper to help with brush limits etc.

Unsure about the GameData one, if that was causing an issue I'd expect it to fail compiling?

**Comment by maxdup** [comment]
So the crash you're experiencing is because CompilePal fails to read one of your mdl file. The compile log tells me that there's a lot of assets that are probably broken in one way or an other so my advice would be sort that out first. Make sure these assets actually work before trying to pak them. then, if you can figure out which asset is causing trouble, that would be useful. I'll give it a shot but atm, I can't really 100% identify the issue.

**Comment by Exactol** [comment]
Closing stale issues
