### ISSUE TITLE
Only entities compile breaks packing

### ISSUE THREAD

**Issue by gortnarj** [ruarai/CompilePal#51]
Error:
Something broke:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CompilePalX.Compilers.BSPPack.BSP.buildModelList() in C:\Users\Jan\Documents\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 210
   at CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file) in C:\Users\Jan\Documents\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 75
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) in C:\Users\Jan\Documents\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 70

**Comment by maxdup** [comment]
Seems like a very interesting problem, I'll have to do some digging and see how -onlyents affects the bsp. guess I'll have to check -onlyprops also

**Comment by maxdup** [comment]
That one threw me for a loop. Turns out that -onlyents and -onlyprops both reorder some of bsps content that I had always assumed would be in the same order. All fixed now.
