### ISSUE TITLE
Issue with packing content

### ISSUE THREAD

**Issue by VaasKahnGrim** [ruarai/CompilePal#81]
**Describe the bug**
I'm attempting to use compile pal to make a list of all models, textures, materials, sounds, and any other file. and rather than pack them I'm aiming to do something else but I need the list. and this error is hindering me.

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterialsAndModels(String path, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\AssetUtils.cs:line 103
   at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 227
   at CompilePalX.Compilers.BSPPack.PakFile..ctor(BSP bsp, List`1 sourceDirectories, List`1 includeFiles, List`1 excludedFiles, List`1 excludedDirs) in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 32
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 153

**Steps to reproduce**
Set the packing stage to use Verbose and Dryrun

**Expected behavior**
Simply to be able to make a list of all files used to create my map

**Debug.txt**
https://pastebin.com/CLj06nUb

**Comment by Exactol** [comment]
What engine is this for, and do you know which model is causing this crash?

**Comment by VaasKahnGrim** [comment]
Garrysmod, and no clue which one. it doesn't say

**Comment by Exactol** [comment]
I pushed a new pre-release version which should tell you which model is causing the issue, please download this https://github.com/ruarai/CompilePal/releases/tag/026.2 and send me the model that is causing the issue.

**Comment by Exactol** [comment]
Closing stale issues
