### ISSUE TITLE
Crashes on compile

### ISSUE THREAD

**Issue by avernus-jcp** [ruarai/CompilePal#90]
An exception was caught by the ExceptionHandler:
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.CompileExecutable.Run(CompileContext c) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\CompileExecutable.cs:line 49
   at CompilePalX.CompilingManager.CompileThreaded() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compiling\CompilingManager.cs:line 115
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Archadimus** [comment]
I've tried running as administrator as well

**Comment by Axzye** [comment]
Very late but you might be able to fix this by turning off your antivirus.

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if it's still happening feel free to reopen the issue
