### ISSUE TITLE
Immediately crashes when launched.

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#98]
**Describe the bug**
When trying to launch the program, it does not open- it shows up for a split second in task manager and then closes.

**Steps to reproduce**
1. open compile pal and boom it crashes.

**Expected behavior**
....that it works.

**Debug.txt**
`An exception was caught by the ExceptionHandler:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.GameConfigurationParser.Parse(String filename) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 155
   at CompilePalX.LaunchWindow..ctor() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 60
An exception was caught by the ExceptionHandler:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.ProgressManager.ErrorProgress() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compiling\ProgressManager.cs:line 74
   at CompilePalX.ExceptionHandler.<LogException>d__0.MoveNext() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\ExceptionHandler.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
An exception was caught by the ExceptionHandler:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.ProgressManager.ErrorProgress() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compiling\ProgressManager.cs:line 74
   at CompilePalX.ExceptionHandler.<LogException>d__0.MoveNext() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\ExceptionHandler.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at CompilePalX.App.Main()
`

**Crash logs**
`
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.GameConfigurationParser.Parse(String filename) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 155
   at CompilePalX.LaunchWindow..ctor() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 60
`

**Comment by Exactol** [comment]
Can you try the latest prerelease?

**Comment by Fennecai** [comment]
> Can you try the latest prerelease?

this was on the prerelease actually. same happens on the non-pre-release.

**Comment by Exactol** [comment]
Can you upload your GameConfig.txt? should be located in the bin folder of the game you are compiling for

**Comment by Fennecai** [comment]
not sure why it matters because i cant even get to the screen where i even choose the game; but ok, ehres portal 2 for example just in case im wrong.

`"Configs"
{
	"Games"
	{
		"Portal 2"
		{
			"GameDir"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\portal2"
			"Hammer"
			{
				"GameData0"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\bin\portal2.fgd"
				"TextureFormat"		"5"
				"MapFormat"		"4"
				"DefaultTextureScale"		"0.250000"
				"DefaultLightmapScale"		"16"
				"GameExe"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\portal2.exe"
				"DefaultSolidEntity"		"func_detail"
				"DefaultPointEntity"		"info_player_start"
				"BSP"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\bin\vbsp.exe"
				"Vis"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\bin\vvis.exe"
				"Light"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\bin\vrad.exe"
				"GameExeDir"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2"
				"MapDir"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\sdk_content\maps"
				"BSPDir"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\portal2\maps"
				"PrefabDir"		"H:\Antonios stuff\program files\Steam\steamapps\common\Portal 2\bin\Prefabs"
				"CordonTexture"		"tools\toolsskybox"
				"MaterialExcludeCount"		"0"
			}
		}
	}
	"SDKVersion"		"4"
}
`

**Comment by Exactol** [comment]
I'm going to close the issue if its working now
